import React from "react";
import Head from "next/head";

import { Navbar, Footer } from "../molecules";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Web3.js Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="fit">{children}</div>
      <Footer />
    </>
  );
};

export { Layout };
