import React from "react";
import Head from "next/head";

import { Navbar, Footer } from "../molecules";
import { Web3ContextProvider } from "../context/web3-context";

const Layout = ({ children }) => {
  return (
    <Web3ContextProvider>
      <div className="max-w-7xl mx-auto">
        <Head>
          <title>Web3.js Demo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div className="fit">{children}</div>
        <Footer />
      </div>
    </Web3ContextProvider>
  );
};

export { Layout };
